Permission model and User Profile
Ballroom-Platform/ballroom-backend pull request #82
Opened 2023-06-09 09:21 UTC by ManujaDewmina

Backend 
- Issue 72 - Assign different scores depend on difficulty of the question
- Issue 76 - Implementing a permission model for contests and challenges
- Issue 79 - Create a Ballroom Asgardeo account.

Frontend
- Issue 45 - View User Profile and move between Admin and Contestant

And several bug fixes and UI improvements

2023-06-20 10:38 UTC, ManujaDewmina commented on user_service/service.bal
Refactor resource function 
- Make role Query parameter optional

2023-06-22 08:15 UTC, sameerajayasoma requested changes

2023-06-22 08:15 UTC, sameerajayasoma commented on upload-service/service.bal
> +        time:Civil nowTime = time:utcToCivil(time:utcNow());
This will not work when the service is running in Choreo. Let's remove this change

2023-06-22 08:15 UTC, sameerajayasoma commented on sts_service/Config_template.txt
> +Authorization = "Basic SG1IUlZjOE1qcFByVGFkcjQxODVvS0xQaW5BYTpSTmhOMkdBcGFyNzRxdkRIcU1FYXd2Ymx6bXdh"
Let's not hardcode the token here :)

2023-06-22 08:15 UTC, sameerajayasoma commented on executor-service/service.bal
> +        entities:Challenge|persist:Error challengeDifficulty = db->/challenges/[challengeId]();
It looks like we need only the difficulty field here. Shall we use a custom type to query only that field?

2023-06-22 08:15 UTC, sameerajayasoma commented on executor-service/service.bal
> +        } else if (challengeDifficulty.difficulty == "EASY") {
Let's remove parenthesis in conditional expressions

2023-06-22 08:15 UTC, sameerajayasoma commented on contest-service/service.bal
> +    resource function get contests/report/[string contestId]()
Let's change the resource path to `contests/[string contestId]/report`

2023-06-22 08:15 UTC, sameerajayasoma commented on contest-service/service.bal
> +            returns http:InternalServerError|string[][]{
There exists code formatting error.

2023-06-22 08:15 UTC, sameerajayasoma commented on contest-service/service.bal
> +    resource function get contests/[string userId]/registered(string status)
Let's remove the status query param, as discussed. It's best to reduce calls from UI to backend.

2023-06-22 08:15 UTC, sameerajayasoma commented on contest-service/service.bal
> +    resource function get contests/[string contestId]/accessGrantedUsers() returns Payload|http:InternalServerError {
How about `users-with-access`?

2023-06-22 08:15 UTC, sameerajayasoma commented on contest-service/service.bal
> +    resource function get contests/[string contestId]/accessGrantedUsers() returns Payload|http:InternalServerError {
We can use the same resource name for the post and delete

2023-06-23 09:48 UTC, sameerajayasoma approved these changes

2023-06-23 09:48 UTC, merged